version: '3'
services:

  mysql-master-db1:
    image: mysql:5.7.22
    volumes:
      - ./conf/master:/etc/mysql/conf.d
      - ./init/mysql/master:/init-mysql
      - ./init/db:/init-db
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      #- ./volume/mysql-master-db1:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '33060:3306'
    networks:
      - debezium-docker-net

  mysql-master-db2:
    image: mysql:5.7.22
    volumes:
      - ./conf/master:/etc/mysql/conf.d
      - ./init/mysql/master:/init-mysql
      - ./init/db:/init-db
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      #- ./volume/mysql-master-db2:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '33061:3306'
    networks:
      - debezium-docker-net

networks:
  debezium-docker-net:
    external:
      name: debezium-docker-net